### PR TITLE
handle participations being an iterable

### LINKED ISSUE #17: IInteraction's participations is an iterable not necessarily an iterator
When [``IInteractions.participations``](https://github.com/zopefoundation/zope.security/blob/master/src/zope/security/interfaces.py#L294) is an iterable (such as a list) the IInteraction to IPrincipal [adapter](https://github.com/NextThought/nti.app.pyramid_zope/blob/master/src/nti/app/pyramid_zope/security.py#L76) breaks.

```
  File "///nti.app.pyramid_zope/src/nti/app/pyramid_zope/i18n/subscribers.py", line 60, in adjust_request_interface_for_preferred_languages
    remote_user = IPrincipal(request, None)
  File "///zope/component/hooks.py", line 135, in adapter_hook
    return siteinfo.adapter_hook(interface, object, name, default)
  File "///nti.app.pyramid_zope/src/nti/app/pyramid_zope/security.py", line 104, in principal_from_request
    return IPrincipal(interaction)
  File "///zope.component-4.6.2-py2.7.egg/zope/component/hooks.py", line 135, in adapter_hook
    return siteinfo.adapter_hook(interface, object, name, default)
  File "///nti.app.pyramid_zope/src/nti/app/pyramid_zope/security.py", line 76, in principal_from_interaction
    return next(interaction.participations).principal
TypeError: list object is not an iterator
```

### PR DESCRIPTION
**Pull request by cutz**
Fixes Issue #17

### CODE REVIEW

**Review by jamadden — COMMENTED** [review]
A functional test that makes sure the adapters work is great, but I would also recommend a unit test (no layer) that just calls the function directly. Those are easier to isolate and debug.

**Comment by cutz** [comment]
Rebased on master

**Review by jamadden — APPROVED** [review]
Love the new test. Since the gha update has been merged, if you can rebase and get green, this is awesome.

**Comment by cutz** [comment]
Thanks! I have a bunch of other changes stacked up locally as part of the ZMI stuff I'm looking into. I'll probably try and clean some of those up and get those pushed here before we take the time to cut a new version.

**Comment by jamadden** [comment]
Love. It.

**Comment by jamadden** [comment]
As a reminder, you're an owner of this project on PyPI. You can release whenever you wish. Just make sure you have proper authentication (historically, `~/.pypirc`), then run the `fullrelease` command from the PyPI requirement `zest.releaser[recommended]`, while in an up-to-date checkout of the main branch working directory.

**Pull request merged**
